# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: wget
        uses: wei/wget@v1
        with:
          args: -O vanilla-tweaks.zip https://vanillatweaks.net/download/VanillaTweaks_r815931.zip
            
      - uses: montudor/action-zip@v1
        with:
          args: unzip -n vanilla-tweaks.zip -d $GITHUB_WORKSPACE

      # Runs a set of commands using the runners shell
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'crater-ressourcepack.zip'
          exclusions: '*.git* *.zip *.xcf *.txt package.json'
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          PACKAGE_FILENAME:  'pack.mcmeta'
        with:
          tag-prefix: 'v'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "crater-ressourcepack.zip"
            
